name = "harbor-soccer"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "harbor-soccer-db"
database_id = "e474fb6f-cbf7-4e44-8d32-27647af56ae5"

[vars]
ADMIN_USERNAME = "admin"
# In production, set ADMIN_PASSWORD via wrangler secret put ADMIN_PASSWORD
ADMIN_PASSWORD = "changeme123"
JWT_SECRET = "your-jwt-secret-change-this"
