# Cloudflare Pages configuration
name = "harbor-soccer-website"
main = "./out"
compatibility_date = "2023-06-14"

# The directory where your built assets will be output
pages_build_output_dir = "out"

[build]
command = "npm run build"

[build.upload]
format = "directory"